blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from . import views


app_name = BlogConfig.name


urlpatterns = [
    path('posts/',
         views.PostsListView.as_view(),
         name='posts',
         ),
    path('posts/create/',
         views.AddPostCreateView.as_view(),
         name='addpost',
         ),
    path('posts/update/<slug:slug_id>/',
         views.UpdatePostView.as_view(),
         name='updatepost',
         ),
    path('posts/delete/<slug:slug_id>/',
         views.DeletePostView.as_view(),
         name='deletepost',
         ),
    path('posts/<slug:slug_id>/',
         views.PostDetailView.as_view(),
         name='post',
         ),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path
from . import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('', include('main_page.urls', namespace='main_page')),
    path('', include('mess.urls', namespace='mess')),
    path('', include('users.urls', namespace='users')),
    path('', include('our_clients.urls', namespace='our_clients')),
    path('', include('mail_center.urls', namespace='mail_center')),
    path('', include('blog.urls', namespace='blog')),
] + (static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +
     static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))

if settings.DEBUG:
    urlpatterns += [path('__debug__/', include('debug_toolbar.urls'))]

our_clients/urls.py
from django.urls import path
from our_clients.apps import OurClientsConfig
from .views import (ClientCreateView,
                    ClientToggleActivityView,
                    ClientUpdateView,
                    ClientsListView,
                    )


app_name = OurClientsConfig.name


urlpatterns = [
    path('clients/',
         ClientsListView.as_view(),
         name='clients',
         ),
    path('clients/create/',
         ClientCreateView.as_view(),
         name='create_client',
         ),
    path('clietns/update/<int:pk>',
         ClientUpdateView.as_view(),
         name='update_client',
         ),
    path('clietns/delete/<int:pk>',
         ClientToggleActivityView.as_view(),
         name='delete_client',
         ),
]

our_clients/models.py
from django.db import models
from django.contrib.auth import get_user_model


class ClientServise(models.Model):
    """Модель клиента для рассылок
    Имеет поля: ФИО, эмеил, описание

    Отношение: our_clients:ClientServise
    """
    employee = models.ForeignKey(get_user_model(),
                                 verbose_name='кем добавлено',
                                 on_delete=models.SET_NULL,
                                 blank=True,
                                 null=True
                                 )
    client_mail = models.EmailField(verbose_name='эмеил клиента',)
    client_first_name = models.CharField(max_length=80,
                                         verbose_name='имя клиента'
                                         )
    client_last_name = models.CharField(max_length=120,
                                        verbose_name='фамилия клиента'
                                        )
    client_middle_name = models.CharField(max_length=120,
                                          verbose_name='отчество клиента',
                                          default=None,
                                          blank=True,
                                          null=True
                                          )
    client_info = models.TextField(blank=True,
                                   null=True,
                                   verbose_name='информания о клиенте'
                                   )
    time_create = models.DateTimeField(auto_now_add=True,
                                       verbose_name='время создания'
                                       )
    time_edit = models.DateTimeField(auto_now=True,
                                     blank=True,
                                     null=True,
                                     verbose_name='время редактирования'
                                     )
    actual = models.BooleanField(default=True,
                                 verbose_name='актуальность'
                                 )

    class Meta:
        verbose_name = 'клиент'
        verbose_name_plural = 'клиенты'
        ordering = ['-time_edit']

    def __str__(self):
        return self.client_mail

our_clients/forms.py
from django import forms
from .models import ClientServise


class AddClientForm(forms.ModelForm):

    class Meta:
        model = ClientServise
        fields = ('client_mail',
                  'client_first_name',
                  'client_last_name',
                  'client_middle_name',
                  'client_info',
                  )

our_clients/views.py
from typing import Any
from django.forms import BaseModelForm
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import (CreateView,
                                  DeleteView,
                                  UpdateView,
                                  ListView,
                                  )
from django.contrib.auth import mixins
from django.db.models import Q

from pytils.translit import slugify

from .models import ClientServise
from .forms import AddClientForm
from .mixins import OwnerOrStaffPermissionMixin, CheckModeratorMixin
from mail_center.cache import get_or_set_cache, delete_cache


class ClientsListView(mixins.LoginRequiredMixin,
                      CheckModeratorMixin,
                      ListView):
    template_name = 'our_clients/clients_list.html'
    model = ClientServise
    context_object_name = 'clients'
    paginate_by = 21
    extra_context = {'title': 'Clients', 'catg_selected': 3}

    def get_queryset(self):
        queryset = get_or_set_cache(ClientServise, is_queryset_all=True)
        if not queryset:
            queryset = super().get_queryset()

        if (not self.request.user.is_staff and
            not self.request.user.is_superuser):
            return (queryset.filter(Q(employee=self.request.user))
                    .order_by('client_first_name')
                    .select_related('employee'))

        return (queryset
                .order_by('client_first_name')
                .select_related('employee'))

    def get_context_data(self, **kwargs) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['content_manager'] = get_or_set_cache(
            self.request.user.groups,
            slug='content-manager',
            type_field='name',
            )
        context['title'] = 'Clients'
        context['catg_selected'] = 3
        return context


class ClientCreateView(mixins.LoginRequiredMixin,
                       CheckModeratorMixin,
                       mixins.UserPassesTestMixin,
                       CreateView):
    model = ClientServise
    form_class = AddClientForm
    template_name = 'our_clients/cliendinfo_form.html'
    success_url = reverse_lazy('our_clients:clients')
    extra_context = {'title': 'ClientCreate', 'catg_selected': 3}

    def form_valid(self, form: BaseModelForm):
        form.instance.employee = self.request.user
        delete_cache(ClientServise, is_queryset_all=True)
        return super().form_valid(form)

    def test_func(self) -> bool | None:
        return (not self.moderator and
                not self.request.user.is_staff or
                self.request.user.is_superuser)


class ClientUpdateView(mixins.LoginRequiredMixin,
                       OwnerOrStaffPermissionMixin,
                       UpdateView):
    model = ClientServise
    form_class = AddClientForm
    template_name = 'our_clients/cliendinfo_form.html'
    context_object_name = 'client_p'
    success_url = reverse_lazy('our_clients:clients')
    extra_context = {'title': 'ClientUpdate', 'catg_selected': 3}

    def form_valid(self, form):
        slug_employee = slugify(form.instance.employee.pk)
        slug_client = slugify(form.instance.client_last_name)
        form.instance.slug = f'{slug_employee}-{slug_client}'
        delete_cache(ClientServise, is_queryset_all=True)
        return super().form_valid(form)

    def test_func(self) -> bool | None:
        return self.request.user.is_superuser or\
                self.request.user == self.get_object().employee


class ClientToggleActivityView(mixins.LoginRequiredMixin,
                               OwnerOrStaffPermissionMixin,
                               DeleteView):
    model = ClientServise
    template_name = 'our_clients/client_delete.html'
    context_object_name = 'client_p'
    success_url = reverse_lazy('our_clients:clients')
    extra_context = {'title': 'update', 'catg_selected': 3}

    def form_valid(self, form):
        if self.object.actual:
            self.object.actual = False
        else:
            self.object.actual = True
        self.object.save(update_fields=['actual'])
        delete_cache(ClientServise, is_queryset_all=True)
        return HttpResponseRedirect(self.get_success_url())

our_clients/templates/includes/our_clients/card_client.html
<div class="g-col-4">
    <div class="card bg-body-tertiary p-3 mb-4" style="height: 370px; padding: 16px 16px 12px; border-radius: 8px; box-shadow: 0 1px 2px 0 rgba(0,0,0,.16);">
        <header class="d-flex align-items-center justify-content-between flex-wrap-nowrap mb-2" style="height: 24px; margin: -4px; padding: 4px;">
            <div class="d-flex" style="margin: 0 4px 0 0; max-width: 100%;">
                <span class="d-flex align-items-center" style="max-width: 100%;">
                    <span class="d-flex flex-column">
                        {% if request.user.is_superuser or moderator %}
                        <div style="margin: 0 5px 0 0; line-height: .9375rem; font-size: .8125rem; font-weight: 700;">{{ client.employee.username }}</div>
                        {% endif %}
                        {% if client.time_edit == client.time_create %}
                        <div style="font-size: .75rem; line-height: .6875rem;">{{ client.time_create }}</div>
                        {% else %}
                        <div style="font-size: .75rem; line-height: .6875rem;">{{ client.time_edit }}</div>
                        {% endif %}
                    </span>
                </span>
            </div>
            <div>
                {% if not content_manager %}
                <div>
                    {% if not moderator %}
                    <a class="btn border" style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;" href="{% url 'our_clients:update_client' client.pk %}">Изменить</a>
                    {% endif %}
                    <a class="btn border" style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;" href="{% url 'our_clients:delete_client' client.pk %}">{% if client.actual %}Деактивировать{% else %}Активировать{% endif %}</a>
                </div>
                {% endif %}
            </div>
        </header>
        <div class="border mb-2" ></div>
        <div class="card-title d-flex justify-content-between">
            <h5>{{ client.client_mail }}</h5>
            {% if client.actual %}
            <p class="text-success">Актуальный</p>
            {% else %}
            <p class="text-danger">Деактивирован</p>
            {% endif %}
        </div>
        <div class="card-body">
            <p>
                Имя: {{ client.client_first_name }}
            </p>
            <p>
                Фамилия: {{ client.client_last_name }}
            </p>
            {% if client.client_middle_name %}
            <p>
                Отчество: {{ client.client_middle_name }}
            </p>
            {% endif %}
        </div>
        <div class="card-footer">
            <p>{{ client.client_info|truncatechars:150 }}</p>
        </div>
    </div>
</div>

our_clients/templates/includes/our_clients/create_client.html
<form class="p-3" action="{% if client_p %}{% url 'our_clients:update_client' client_p.pk %}{% else %}{% url 'our_clients:create_client' %}{% endif %}" method="post">
    {% csrf_token %}
    <input type="hidden" name="text" value="{{ next }}"/>
    {% if form.non_field_errors %}
        <div class="form-error" style="font-size: 14px;"><strong>{{ form.non_field_errors }}</strong></div>
    {% endif %}
    <p>
        <label class="form-label" for="id_client_mail">Эмеил клиента:*</label>
        <input class="form-control" type="email" name="client_mail" maxlength="254" {% if client_p %}value="{{ client_p.client_mail }}"{% endif %} required id="id_client_mail">
        {% if form.errors.client_mail %}
        <div>
            <div class="form-error" style="font-size: 14px;"><strong>{{ form.errors.client_mail }}</strong></div>
        </div>
        {% endif %}
    </p>
    <p>
        <label class="form-label" for="id_client_first_name">Имя клиента:*</label>
        <input class="form-control" type="text" name="client_first_name" maxlength="80" {% if client_p %}value="{{ client_p.client_first_name }}"{% endif %} required id="id_client_first_name">
        {% if form.errors.client_first_name %}
        <div>
            <div class="form-error" style="font-size: 14px;"><strong>{{ form.errors.client_first_name }}</strong></div>
        </div>
        {% endif %}
    </p>
    <p>
        <label class="form-label" for="id_client_last_name">Фамилия клиента:*</label>
        <input class="form-control" type="text" name="client_last_name" maxlength="120" {% if client_p %}value="{{ client_p.client_last_name }}"{% endif %} required id="id_client_last_name">
        {% if form.errors.client_last_name %}
        <div>
            <div class="form-error" style="font-size: 14px;"><strong>{{ form.errors.client_last_name }}</strong></div>
        </div>
        {% endif %}
    </p>
    <p>
        <label class="form-label" for="id_client_middle_name">Отчество клиента:</label>
        <input class="form-control" type="text" name="client_middle_name" maxlength="120" {% if client_p and client_p.client_middle_name %}value="{{ client_p.client_middle_name }}"{% endif %} id="id_client_middle_name">
        {% if form.errors.client_middle_name %}
        <div>
            <div class="form-error" style="font-size: 14px;"><strong>{{ form.errors.client_middle_name }}</strong></div>
        </div>
        {% endif %}
    </p>
    <p>
        <label class="form-label" for="id_client_info">Информания о клиенте:</label>
        <textarea class="form-control" name="client_info" cols="40" rows="10" id="id_client_info">{% if client_p %}{{ client_p.client_info }}{% endif %}</textarea>
        {% if form.errors.client_info %}
        <div>
            <div class="form-error" style="font-size: 14px;"><strong>{{ form.errors.client_info }}</strong></div>
        </div>
        {% endif %}
    </p>
    <button class="btn btn-success" type="submit">Создать</button>
    <a class="btn border" style="box-shadow: 0 1px 2px 0 rgba(0,0,0,.16);" href="{% url 'our_clients:clients' %}">Отмена</a>
</form>