blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from . import views


app_name = BlogConfig.name


urlpatterns = [
    path('posts/',
         views.PostsListView.as_view(),
         name='posts',
         ),
    path('posts/create/',
         views.AddPostCreateView.as_view(),
         name='addpost',
         ),
    path('posts/update/<slug:slug_id>/',
         views.UpdatePostView.as_view(),
         name='updatepost',
         ),
    path('posts/delete/<slug:slug_id>/',
         views.DeletePostView.as_view(),
         name='deletepost',
         ),
    path('posts/<slug:slug_id>/',
         views.PostDetailView.as_view(),
         name='post',
         ),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path
from . import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('', include('main_page.urls', namespace='main_page')),
    path('', include('mess.urls', namespace='mess')),
    path('', include('users.urls', namespace='users')),
    path('', include('our_clients.urls', namespace='our_clients')),
    path('', include('mail_center.urls', namespace='mail_center')),
    path('', include('blog.urls', namespace='blog')),
] + (static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +
     static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))

if settings.DEBUG:
    urlpatterns += [path('__debug__/', include('debug_toolbar.urls'))]

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from . import views
from django.contrib.auth.views import LogoutView


app_name = UsersConfig.name


urlpatterns = [
    # login - logout
    path('login/',
         views.AuthView.as_view(),
         name='login'),
    path('logout/',
         LogoutView.as_view(),
         name='logout',
         ),
    # registration
    path('regisration/',
         views.RegisterUser.as_view(),
         name='reg',
         ),
    path('regisration/done/',
         views.UserRegistrationDode.as_view(),
         name='done',
         ),
    path('regisration/verify/<uidb64>/<token>/',
         views.UserConfirmEmailView.as_view(),
         name='verify_email',
         ),
    # user
    path('users/',
         views.UserListView.as_view(),
         name='users_list',
         ),
    path('user/<str:username>/',
         views.UserDetailView.as_view(),
         name='user',
         ),
    path('user/<str:username>/update/',
         views.UpdateProfileUser.as_view(),
         name='update',
         ),
    # password_gate
    path('password_way/',
         views.UserChoiceWayView.as_view(),
         name='password_way',
         ),
    # password_change
    path('password_change/',
         views.UserChangePassword.as_view(),
         name='password_change',
         ),
    path('password_change/done/',
         views.UserChangePasswordDone.as_view(),
         name='password_change_done',
         ),
    # password_reset
    path('password_reset/',
         views.UserResetPassword.as_view(),
         name='password_reset',
         ),
    path('password_reset/done/',
         views.UserResetPasswordDone.as_view(),
         name='password_reset_done',
         ),
    path('password_reset/complete/',
         views.UserResetPasswordComplete.as_view(),
         name='password_reset_complete',
         ),
    path('password_reset/<uidb64>/<token>/',
         views.UserResetPasswordConfirm.as_view(),
         name='password_reset_confirm',
         ),
    path('password_temporary/',
         views.UserPasswordTemporary.as_view(),
         name='verify_temporary',
         ),
    path('password_temporary_done/<uidb64>/<token>/',
         views.UserPasswordTemporaryDone.as_view(),
         name='verify_temporary_done',
         ),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

from django.urls import reverse
from phonenumber_field.modelfields import PhoneNumberField
from django_countries.fields import CountryField


class User(AbstractUser):
    """Модель пользователя
    """
    image = models.ImageField(upload_to='users/',
                              blank=True, null=True,
                              verbose_name='аватар'
                              )
    email = models.EmailField(max_length=254,
                              unique=True,
                              verbose_name='эмеил'
                              )
    is_verify_email = models.BooleanField(default=False,
                                          verbose_name='подтвержденный эмеил'
                                          )
    phone = PhoneNumberField(null=True,
                             blank=False,
                             verbose_name='номер телефона'
                             )
    country = CountryField(verbose_name='страна',
                           null=True,
                           blank=True,
                           blank_label='(select country)'
                           )
    gender = models.CharField(verbose_name='пол',
                              choices=(('men', 'Мужчина'),
                                       ('women', 'Женщина'),
                                       (None, 'Не выбрано')),
                              null=True,
                              blank=True,
                              default=None
                              )

    class Meta:
        db_table = 'user'
        verbose_name = 'пользователь'
        verbose_name_plural = 'пользователи'

    def get_absolute_url(self):
        return reverse("users:user", kwargs={"username": self.username})

users/views.py
from django.db.models.query import QuerySet, Q
from django.http import HttpRequest, HttpResponseRedirect
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator, decorator_from_middleware
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.contrib.auth import update_session_auth_hash
from django.utils.encoding import force_bytes
from django.middleware.csrf import CsrfViewMiddleware
from django.views.generic import (TemplateView,
                                  DetailView,
                                  CreateView,
                                  UpdateView,
                                  ListView
                                  )
from django.contrib.auth import get_user_model, mixins
from django.utils.http import int_to_base36
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.views import (LoginView,
                                       PasswordChangeView,
                                       PasswordChangeDoneView,
                                       PasswordResetView,
                                       PasswordResetDoneView,
                                       PasswordResetConfirmView,
                                       PasswordResetCompleteView,
                                       PasswordContextMixin
                                       )

from typing import Any

from users.mixins import RequiredNotAuthenticatedMixin
from .forms import (UserChangePasswordForm,
                    UserLoginForm,
                    RegisterUserForm,
                    UserUpdateForm)
from users.tasks import send_verify_email
from mail_center.cache import get_or_set_cache

import random


csrf_protect = decorator_from_middleware(CsrfViewMiddleware)

VERIFY_EMAIL_SESSION_TOKEN = '_verify_session_token'


class UserDetailView(DetailView):
    model = get_user_model()
    slug_url_kwarg = 'username'
    slug_field = 'username'
    context_object_name = 'current_user'

    def post(self, request: HttpRequest, *args: str, **kwargs):
        obj = self.get_object()

        if not obj.is_verify_email:
            return redirect('users:user', **{
                'username': self.kwargs['username'],
                })

        if obj.is_active:
            obj.is_active = False
        else:
            obj.is_active = True

        obj.save(update_fields=['is_active'])

        return redirect('users:user', **{
            'username': self.kwargs['username']},
                        )

    def get_context_data(self, **kwargs):
        content_manager = get_or_set_cache(
            self.request.user.groups,
            slug='content-manager',
            type_field='name',
            )
        context = super().get_context_data(**kwargs)
        context['title'] = 'Profile'
        context['content_manager'] = content_manager
        return context


class UserListView(mixins.LoginRequiredMixin,
                   mixins.UserPassesTestMixin,
                   ListView):
    model = get_user_model()
    context_object_name = 'users'
    paginate_by = 30

    def get_queryset(self) -> QuerySet[Any]:
        queryset = super().get_queryset()
        queryset = queryset.filter(Q(is_superuser=False) &
                                   Q(is_staff=False)).order_by('-is_active')
        return queryset

    def test_func(self) -> bool | None:
        return self.request.user.is_superuser or self.request.user.is_staff


class AuthView(RequiredNotAuthenticatedMixin, LoginView):
    template_name = 'users/login.html'
    form_class = UserLoginForm

    extra_context = {'title': 'Authentication'}

    def get_success_url(self) -> str:
        return reverse_lazy('mail_center:mails')


class RegisterUser(mixins.UserPassesTestMixin,
                   PasswordContextMixin,
                   CreateView):
    form_class = RegisterUserForm
    template_name = 'users/register_user.html'
    email_template_name = "check_mail/register_check_email.html"
    subject_template_name = "registration/password_reset_subject.txt"
    success_url = reverse_lazy('users:done')
    title = ('Завершение регистрации')
    token_generator = default_token_generator
    extra_context = {'title': 'Registration'}

    @method_decorator(csrf_protect)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def form_valid(self, form):
        email = form.cleaned_data.get('email')

        form.instance.is_active = False
        form.save()

        user = get_user_model()._default_manager.get(email=email)
        username = user.username
        current_site = 'localhost'
        site_name = 'Messender'
        update_session_auth_hash(self.request, user)

        context = {
                "email": email,
                "domain": current_site,
                "site_name": site_name,
                "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                "user": username,
                "token": self.token_generator.make_token(user),
                "protocol": "https" if self.request.is_secure() else "http",
            }

        send_verify_email.apply_async(
            kwargs={'email': email,
                    'context': context,
                    'email_template_name': 'check_mail/register_check_email.html',
                    })

        self.object = form
        return HttpResponseRedirect(self.get_success_url())

    def test_func(self) -> bool | None:
        return (not self.request.user.is_authenticated or
                self.request.user.is_superuser or
                self.request.user.is_staff)


class UserConfirmEmailView(RequiredNotAuthenticatedMixin, TemplateView):
    template_name = 'check_mail/verify_done.html'
    reset_url_token = "verify_email"
    token_generator = default_token_generator
    extra_context = {'title': 'ConfirmEmail'}

    def dispatch(self, *args, **kwargs):
        self.valid = False
        self.user = self.get_user(kwargs['uidb64'])
        if self.user is not None:
            token = kwargs['token']
            if token == self.reset_url_token:
                session_token = self.request.session.get(
                    VERIFY_EMAIL_SESSION_TOKEN,
                    )
                if self.token_generator.check_token(
                   self.user, session_token,
                   ):
                    self.valid = True
                    self.user.is_active = True
                    self.user.is_verify_email = True
                    self.user.save(update_fields=(
                        'is_active',
                        'is_verify_email',
                        ))
                    del self.request.session[VERIFY_EMAIL_SESSION_TOKEN]
            else:
                if self.token_generator.check_token(self.user, token):
                    self.request.session[VERIFY_EMAIL_SESSION_TOKEN] = token
                    redirect_url = self.request.path.replace(
                        token, self.reset_url_token
                    )
                    return HttpResponseRedirect(redirect_url)

        return self.render_to_response(self.get_context_data())

    def get_user(self, uidb64):
        uid = urlsafe_base64_decode(uidb64).decode()
        try:
            user = get_user_model()._default_manager.get(pk=uid)
        except:
            user = None
        return user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_valid'] = self.valid
        if self.valid:
            context['message'] = 'Регистрация завершена!'
        else:
            context['message'] = 'Регистрация не может быть завершена'
        return context


class UserRegistrationDode(RequiredNotAuthenticatedMixin, TemplateView):
    template_name = 'check_mail/register_done.html'


class UpdateProfileUser(mixins.LoginRequiredMixin,
                        mixins.UserPassesTestMixin,
                        UpdateView):
    model = get_user_model()
    form_class = UserUpdateForm
    context_object_name = 'user_edit'
    slug_field = 'username'
    slug_url_kwarg = 'username'
    template_name = 'users/change_profile.html'
    extra_context = {'title': 'UpdateProfile'}

    def test_func(self) -> bool | None:
        obj = self.get_object()
        return self.request.user == obj or self.request.user.is_superuser

    def get_success_url(self) -> str:
        return reverse_lazy('users:user',
                            kwargs={
                                'username': self.kwargs.get('username'),
                                },
                            )


class UserChoiceWayView(TemplateView):
    template_name = 'passwords/password_choice_way.html'


class UserChangePassword(PasswordChangeView):
    form_class = UserChangePasswordForm
    template_name = 'passwords/password_change_form.html'
    success_url = reverse_lazy("users:password_change_done")
    extra_context = {'title': 'ChangePassword'}


class UserChangePasswordDone(PasswordChangeDoneView):
    template_name = 'passwords/password_change_done.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        update_session_auth_hash(self.request, self.request.user)
        context["title"] = 'Done'
        return context


class UserResetPassword(PasswordResetView):
    template_name = 'passwords/password_reset_form.html'
    email_template_name = 'passwords/password_reset_email.html'
    success_url = reverse_lazy('users:password_reset_done')


class UserResetPasswordDone(PasswordResetDoneView):
    template_name = 'passwords/password_reset_done.html'


class UserResetPasswordConfirm(PasswordResetConfirmView):
    template_name = 'passwords/password_reset_confirm.html'
    success_url = reverse_lazy("users:password_reset_complete")


class UserResetPasswordComplete(PasswordResetCompleteView):

users/templates/includes/users/edit_user.html
{% load static %}
{% load countries %}
<div class="container">
  <div class="card p-3">
    <div class="offset-1 col-10">
      <h3 class="p-2">
          Изменения данных пользователя
      </h3>
      <div class="card bg-body-tertiary m-1 p-2 ps-4" style="border-radius: 8px; box-shadow: 0 1px 2px 0 rgba(0,0,0,.16);">
          <form action="{% url 'users:update' user_edit.username %}" method="post" enctype="multipart/form-data">
              {% csrf_token %}
              <input type="hidden" name="next" value="{{ next }}" />
      
              {% if form.non_field_errors %}
              <div class="form-error">{{ form.non_field_errors }}</div>
              {% endif %}
          <div class="card-body p-2 card_big_style">
                   
                <div class="card_big_images">
                  <label class="form-label" style="line-height: .9375rem; font-size: .8125rem; font-weight: 700;" for="id_image">Изображение</label>
                  {% if user_edit.image %}
                      <a href="{{ user_edit.image.url }}">
                          <img src="{{ user_edit.image.url }}" class="d-block w-auto card-style-image" alt="{{ user_edit.username }}">
                      </a>
                      <div class="form-check form-switch mt-2">
                        <input class="form-check-input" type="checkbox" name="image-clear" id="image-clear_id">
                        <label class="form-check-label" style="line-height: .9375rem; font-size: .8125rem; font-weight: 700;" for="image-clear_id">Удалить</label>
                      </div>
                    <span style="line-height: .9375rem; font-size: .8125rem; font-weight: 700;">Изменить:</span>
                  {% else %}
                      <img src="{% static 'images/image_not_found.jpeg' %}" class="d-block w-auto card-style-image" alt="{{ user_edit.username }}">
                  {% endif %}
                    <input style="font-size: 0.60rem;" class="form-control form-control-sm" type="file" name="image" accept="image/*" id="id_image">
                    <div class="form-error">{{ form.image.errors }}</div>
                  </div>
      
                  <div class="col-md-6" style="grid-area: spec-brand">
                      <div class="d-flex flex-column">
                        <div>
                          <p style="line-height: .9375rem; font-size: .8125rem; font-weight: 700;">Имя пользователя:<strong class="ms-2">{{ user_edit.username }}</strong></p>
                        </div>
                        <div class="mt-2">
                          <p style="line-height: .9375rem; font-size: .8125rem; font-weight: 700;">Телефон:<strong class="ms-2">{{ user_edit.phone }}</strong></p>
                        </div>
                        <div class="mt-2">
                          <p style="line-height: .9375rem; font-size: .8125rem; font-weight: 700;">Эмеил:<strong class="ms-2">{{ user_edit.email}}</strong></p>
                        </div>
                      </div>
                  </div>
      
                  <div class="col-md-6 mt-2 form-floating" style="grid-area:stat;">
                    <input class="form-control" style="font-size: .80rem;" type="text" {% if user_edit.first_name %}value="{{ user_edit.first_name }}"{% endif %} name="first_name" maxlength="150" id="id_first_name">
                    <label style="font-size: .80rem;" for="id_first_name">Имя:</label>
                    <div class="form-error">{{ form.first_name.errors }}</div>
                  </div>
      
                  <div class="col-md-6 mt-2 form-floating" style="grid-area:info;">
                    <input class="form-control" style="font-size: .80rem; line-height: 1.250rem;" type="text" {% if user_edit.last_name %}value="{{ user_edit.last_name }}"{% endif %} name="last_name" maxlength="150" id="id_last_name">
                    <label style="font-size: .80rem; line-height: 1.250rem;" for="id_last_name">Фамилия:</label>
                    <div class="form-error">{{ form.last_name.errors }}</div>
                  </div>
      
                  <div class="col-md-6 mt-2 form-floating" style="grid-area:buy;">
                    <select class="form-select form-select-sm" name="country"  id="id_country">
                      <option value="{% if user_edit.country %}{{ user_edit.country }}{% endif %}" selected>{% if user_edit.country %}{{ user_edit.country }}{% else %}-----{% endif %}</option>
                      {% get_countries as countries %}
                      {% for country in countries %}
                      <option value="{{ country.code }}">{{ country.name }}</option>
                      {% endfor %}   
                    </select>
                    <label class="form-label" style="font-size: .80rem; line-height: 1.250rem;" for="id_country">Страна</label>
                  </div>
                  <div class="form-error">{{ form.country.errors }}</div>

                  <div class="col-md-6 mt-2 form-floating" style="grid-area:wrap;">
                    <select class="form-select form-select-sm" name="gender"  id="id_gender">
                    {% for gen in form.gender %}
                      {{ gen }}
                    {% endfor %}
                    </select>
                    <label class="form-label" style="font-size: .80rem; line-height: 1.250rem;" for="id_country">Пол</label>
                  </div>
                  <div class="form-error">{{ form.country.errors }}</div>
            </div>
            <div class="mt-5">
              <button class="btn btn-secondary ms-2" type="submit">Сохранить</button>
              <a href="{% url 'users:user' user_edit.username %}" class="btn border" style="box-shadow: 0 1px 2px 0 rgba(0,0,0,.16);">Отменить</a>
            </div>
          </form>
      </div>
    </div>
  </div>
</div>

users/templates/includes/users/form_register.html
{% load static %}
{% load countries %}

<h3 class="text-center">Регистрация</h3>
<div class="card mt-2 p-2">
    <form class="offset-3 col-md-6 card-body mb-4 p-2" action="{% url 'users:reg' %}" method="post">
        <div class="card-title">
            <p class="text-center" style="font-size: 15px;">
                <strong>Все поля данной формы являются обязательными</strong>
            </p>
        </div>
        {% csrf_token %}

            <input type="hidden" name="next" value="{{ next }}" />

            {% if form.non_field_errors %}
            <div class="form-error">{{ form.non_field_errors }}</div>
            {% endif %}
                <div class="form-floating">
                    <input class="form-control" {% if form.username.value %}value="{{ form.username.value }}"{% endif %} type="text" name="username" placeholder="{{ form.username.label }}" autofocus="true" required {% if value.username %}value="{{ value.username }}"{% endif %} id="id_username">
                    <label class="form-label text-secondary" for="id_username">{{ form.username.label }}</label>
                </div>
                <div class="form-error">{{ form.username.errors }}</div>
    
                <div class="form-floating mt-2">
                    <input class="form-control" type="email" {% if form.email.value %}value="{{ form.email.value }}"{% endif %} name="email" placeholder="{{ form.email.label }}" maxlength="254" {% if value.email %}value="{{ value.email }}"{% endif %} id="id_email">
                    <label class="form-label text-secondary" for="id_email">{{ form.email.label }}</label>
                </div>
                <div class="form-error">{{ form.email.errors }}</div>
    
                <div class="input-group mt-2">
                    {{ form.phone }}
                </div>
                <div class="form-error">{{ form.phone.errors }}</div>   
    
                <div class="form-floating mt-2">
                    <input class="form-control" type="password" placeholder="{{ form.password1.label }}" name="password1" required id="id_password1">
                    <label class="form-label text-secondary" for="id_password1">{{ form.password1.label }}</label>
                </div>
                <div class="form-error">{{ form.password1.errors }}</div>
                
                <div class="form-floating mt-2">
                    <input class="form-control" type="password" placeholder="{{ form.password2.label }}" name="password2" required id="id_password2">
                    <label class="form-label text-secondary" for="id_password2">{{ form.password2.label }}</label>
                </div>
                <div class="form-error">{{ form.password2.errors }}</div>    
            <div class="col-md-12">
                <button class="btn mt-2 border" style="box-shadow: 0 1px 2px 0 rgba(0,0,0,.16);" type="submit">Регистрация</button>
            </div>
    </form>
    <div class="card-footer">
        <div class="offset-2 col-md-8">
            <p style="font-size: 13px;">При регистрации вам будет выслано на указаный Эмеил письмо с подтвеждением, будьте уверены что вы указываете правильный почтовый адресс.</p>
            <p style="font-size: 14px;"><strong>Совершая регистрацию вы соглашаетесь на <a href="">обработку персональных данных и сбор статистики</a></strong></p>
            <p style="font-size: 13px;">Если у вас есть дополнительные вопросы вы можете обратиться на наш электронный адресс MessenderInfo@mess.com</p>
        </div>
        
    </div>
</div>

users/templates/includes/users/includes_login.html
{% load static %}

<div class="container">
    <div>
        <div class="d-flex align-items-center">
            <div class="card offset-4 col-4 p-3">
                <div class="card-title">
                    <h4>Авторизация</h4>
                </div>
                <div class="card-body">
                    <form action="{% url 'users:login' %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="text" value="{{ next }}"/>
                        {% if form.non_field_errors %}
                            <div class="form-error" style="font-size: 14px;"><strong>{{ form.non_field_errors }}</strong></div>
                        {% endif %}
                        <p>
                            <label class="form-label" for="id_username">Имя пользователя или Эмеил</label>
                            <input class="form-control" type="text" {% if form.username.value %}value="{{ form.username.value }}"{% endif %} name="username" autofocus="true" autocapitalize="none" autocomplete="username" maxlength="150" required id="id_username">
                        </p>
                        <p>
                            <label class="form-label" for="id_password">Пароль</label>
                            <input class="form-control" type="password" name="password" autocomplete="current-password" required id="id_password">
                        </p>
                        <button class="offset-1 col-md-10 btn btn-success border mt-2" type="submit">Войти</button>
                        <div class="d-flex justify-content-between">
                            <a class="btn border btn-sm mt-2 ms-4" style="box-shadow: 0 1px 2px 0 rgba(0,0,0,.16);" href="{% url 'users:reg' %}">Регистрация</a>
                            <a class="btn border btn-sm mt-2 me-4" style="box-shadow: 0 1px 2px 0 rgba(0,0,0,.16);" href="{% url 'users:password_way' %}">Забыли пароль</a>
                        </div>
                    </form>
                </div>
                <div class="card-footer mt-4">
                    <p style="font-size: 12px;">Данный сервис предоставляет доступ к различной функциональности по рассылке сообщений клиентам.</p>
                    <p style="font-size: 12px;"><strong>Если по каким то причинам у вас возникли проблемы с авторизацией, вы можете обратится по адресу: MessenderHelp@mess.com</strong></p>
                </div>
            </div>
        </div>
    </div>
</div>

users/templates/includes/users/profile_user.html
{% load static %}
<div class="container">
  <div class="card p-3">
    <div class="offset-1 col-10">

      <h3 class="p-2">
          Личный кабинет пользователя
      </h3>
      <div class="card bg-body-tertiary m-1 p-2" style="border-radius: 8px; box-shadow: 0 1px 2px 0 rgba(0,0,0,.16);">
          <div class="card-body p-3 card_big_style">
              <div class="my-3 card_big_images">
                      {% if current_user.image %}
                      <img src="{{ current_user.image.url }}" class="d-block w-auto card-style-image" alt="{{ current_user.username }}">
                      {% else %}
                      <img src="{% static 'images/image_not_found.jpeg' %}" class="d-block w-auto card-style-image" alt="{{ current_user.username }}">
                      {% endif %}
              </div>
              <div style="grid-area: spec-brand">
                <div class="d-flex justify-content-between">
                  <div>
                    <p style="line-height: .9375rem; font-size: .8125rem; font-weight: 700;">Имя пользователя: <strong>{{ current_user.username }}</strong></p>
                    <p style="font-size: .80rem; line-height: .6875rem;">Дата регистрации: {{ current_user.date_joined }}</p>
                  </div>
                  {% if not content_manager %}
                  {% if request.user == current_user or request.user.is_superuser %}
                  <div>
                    <a class="btn border" style="box-shadow: 0 1px 2px 0 rgba(0,0,0,.16);" href="{% url 'users:update' current_user.username %}">Изменить личные данные</a>
                  </div>
                  {% elif request.user.is_staff and not current_user.is_staff and not current_user.is_superuser and current_user.is_verify_email %}
                  <form action="{{ current_user.get_absolute_url }}" method="post">
                    {% csrf_token %}
                    <button class="btn border" style="box-shadow: 0 1px 2px 0 rgba(0,0,0,.16);" role="button">{% if current_user.is_active %}Заблокировать{% else %}Разблокировать{% endif %}</button>
                  </form>
                  {% endif %}
                  {% endif %}
                </div>
              </div>
      
              {% if request.user == current_user or request.user.is_staff %}
              <div class="d-flex flex-column" style="grid-area:stat;">
                <div class="d-flex">
                  <div style="font-size: .80rem; line-height: 1.250rem;">Эмеил: {% if current_user.email %}{{ current_user.email }}{% else %} не указан{% endif %}</div>
                </div>
                
                <div style="font-size: .80rem; line-height: 1.250rem;">Телефон: {% if current_user.phone %}{{ current_user.phone }}{% else %} не указан{% endif %}</div>
                {% endif %}
                <div style="font-size: .80rem; line-height: 1.250rem;">Страна: {% if current_user.country %}{{ current_user.country }}{% else %} не указан{% endif %}</div>
                <div style="font-size: .80rem; line-height: 1.250rem;">Имя: {% if current_user.get_short_name %}{{ current_user.get_short_name }}{% else %} не указан{% endif %}</div>
                <div style="font-size: .80rem; line-height: 1.250rem;">Фамилия: {% if current_user.last_name %}{{ current_user.last_name }}{% else %} не указан{% endif %}</div>
                {% if request.user == current_user %}
                <a class="link-primary link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover" style="font-size: .80rem; line-height: 1.250rem;" href="{% url 'users:password_change' %}">Изменить пароль</a>
                {% endif %}
              </div>
          </div>
      </div>
    </div>
  </div>
</div>