blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from . import views


app_name = BlogConfig.name


urlpatterns = [
    path('posts/',
         views.PostsListView.as_view(),
         name='posts',
         ),
    path('posts/create/',
         views.AddPostCreateView.as_view(),
         name='addpost',
         ),
    path('posts/update/<slug:slug_id>/',
         views.UpdatePostView.as_view(),
         name='updatepost',
         ),
    path('posts/delete/<slug:slug_id>/',
         views.DeletePostView.as_view(),
         name='deletepost',
         ),
    path('posts/<slug:slug_id>/',
         views.PostDetailView.as_view(),
         name='post',
         ),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path
from . import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('', include('main_page.urls', namespace='main_page')),
    path('', include('mess.urls', namespace='mess')),
    path('', include('users.urls', namespace='users')),
    path('', include('our_clients.urls', namespace='our_clients')),
    path('', include('mail_center.urls', namespace='mail_center')),
    path('', include('blog.urls', namespace='blog')),
] + (static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +
     static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))

if settings.DEBUG:
    urlpatterns += [path('__debug__/', include('debug_toolbar.urls'))]

mail_center/urls.py
from django.urls import path
from mail_center.apps import MailCenterConfig
from mail_center.views import (ListSendMessages,
                               CreateSend,
                               UpdateSend,
                               ViewSend,
                               DeleteSend,
                               )


app_name = MailCenterConfig.name


urlpatterns = [
    path('mails/',
         ListSendMessages.as_view(),
         name='mails',
         ),
    path('mails/detail/<slug:slug>/',
         ViewSend.as_view(),
         name='mail_detail',
         ),
    path('mails/create/<slug:slug>/',
         CreateSend.as_view(),
         name='mail_create',
         ),
    path('mails/update/<slug:slug>/',
         UpdateSend.as_view(),
         name='mail_update',
         ),
    path('mails/delete/<slug:slug>/',
         DeleteSend.as_view(),
         name='mail_delete',
         ),
]

main_page/urls.py
from django.urls import path

from main_page.apps import MainPageConfig
from . import views


app_name = MainPageConfig.name


urlpatterns = [
    path('', views.MainPageView.as_view(), name='main'),
]

main_page/views.py
from typing import Any
from django.views.generic import TemplateView
from django.db.models import Q
from django.contrib.auth import get_user_model

from mail_center.models import SendingMessage
from our_clients.models import ClientServise
from blog.models import Posts


class MainPageView(TemplateView):
    template_name = 'main_page/main_page.html'

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['title'] = 'Main'
        context['catg_selected'] = 1
        context['users'] = (get_user_model().objects
                            .filter(~Q(is_staff=True) &
                                    ~Q(is_superuser=True) &
                                    ~Q(is_active=False))
                            .count())
        context['active_newslatters'] = (SendingMessage.objects
                                         .filter(Q(status='run'))
                                         .count())
        context['wait_newslatters'] = (SendingMessage.objects
                                       .filter(~Q(status='run') &
                                               ~Q(status='end'))
                                       .count())
        context['clients_give_newslatter'] = (ClientServise.objects
                                              .filter(~Q(actual=False))
                                              .count())
        try:
            best_posts = (Posts.objects.filter(is_published=True)
                          .order_by('-views')[:3]
                          .select_related('name_user'))
        except:
            best_posts = (Posts.objects.filter(is_published=True)
                          .select_related('name_user'))
        context['best_posts'] = best_posts
        return context

main_page/templates/main_page/main_page.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="main-page-container">
    <div class="main-page-content">

        <h3 class="text-center">Главная страница</h3>
        <header class="main-page-header">

            <div class="main-page-discover">
                <div class="main-page-discover-card">
                    <div class="main-page-discover-card-main">
                        <svg aria-hidden="true" width="48" height="48" viewBox="0 0 512 512"><!--!Font Awesome Free 6.5.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M16.1 260.2c-22.6 12.9-20.5 47.3 3.6 57.3L160 376V479.3c0 18.1 14.6 32.7 32.7 32.7c9.7 0 18.9-4.3 25.1-11.8l62-74.3 123.9 51.6c18.9 7.9 40.8-4.5 43.9-24.7l64-416c1.9-12.1-3.4-24.3-13.5-31.2s-23.3-7.5-34-1.4l-448 256zm52.1 25.5L409.7 90.6 190.1 336l1.2 1L68.2 285.7zM403.3 425.4L236.7 355.9 450.8 116.6 403.3 425.4z"/></svg>
                        <h2 class="main-page-discover-card-main-text">Отправляйте почту вашим клиентам без проблем</h2>
                        <a href="{% url 'mail_center:mails' %}" class="main-page-discover-card-main-button">Перейти к рассылкам</a>
                    </div>
                </div>
                <div class="main-page-discover-card">
                    <div class="main-page-discover-card-main">
                        <svg aria-hidden="true" width="48" height="48"viewBox="0 0 640 512"><path d="M96 64c0-17.7 14.3-32 32-32H448h64c70.7 0 128 57.3 128 128s-57.3 128-128 128H480c0 53-43 96-96 96H192c-53 0-96-43-96-96V64zM480 224h32c35.3 0 64-28.7 64-64s-28.7-64-64-64H480V224zM32 416H544c17.7 0 32 14.3 32 32s-14.3 32-32 32H32c-17.7 0-32-14.3-32-32s14.3-32 32-32z"/></svg>
                        <h2 class="main-page-discover-card-main-text">Отдыхайте и пейте кофе в нашем блоге</h2>
                        <a href="{% url 'blog:posts' %}" class="main-page-discover-card-main-button">Посмотреть блог</a>
                    </div>
                </div>
            </div>
            <h1 class="text-center main-page-h1">
                Получайте удовольствие и зарабатывайте на этом
            </h1>
            <div class="main-page-table">
                <div class="main-page-table-tabs">
                    <div class="main-page-table-tabs-title">{{ users }}+</div>
                    <div class="main-page-table-tabs-desc">Пользователей которые обожают наш сервис</div>
                </div>
                <div class="main-page-table-tabs">
                    <div class="main-page-table-tabs-title">{{ active_newslatters }}+</div>
                    <div class="main-page-table-tabs-desc">Рассылок запущено для клиентов</div>
                </div>
                <div class="main-page-table-tabs">
                    <div class="main-page-table-tabs-title">{{ wait_newslatters }}+</div>
                    <div class="main-page-table-tabs-desc">Рассылок которые будут запущены в будущем</div>
                </div>
                <div class="main-page-table-tabs">
                    <div class="main-page-table-tabs-title">{{ clients_give_newslatter }}+</div>
                    <div class="main-page-table-tabs-desc">Клиентов для которых рассылка приходит вовремя</div>
                </div>
            </div>
        </header>
        <section class="main-page-selection">
            <div class="main-page-part-two">
                <div class="main-page-part-two-command">
                    <h2>MailSender</h2>
                    <p class="main-page-part-two-command-title">Команда на которую можно положиться</p>
                    <div class="main-page-part-two-info">
                        <div class="main-page-part-two-info-card">
                            <svg aria-hidden="true" width="30" height="30" viewBox="0 0 512 512"><path d="M64 32C28.7 32 0 60.7 0 96v64c0 35.3 28.7 64 64 64H448c35.3 0 64-28.7 64-64V96c0-35.3-28.7-64-64-64H64zm280 72a24 24 0 1 1 0 48 24 24 0 1 1 0-48zm48 24a24 24 0 1 1 48 0 24 24 0 1 1 -48 0zM64 288c-35.3 0-64 28.7-64 64v64c0 35.3 28.7 64 64 64H448c35.3 0 64-28.7 64-64V352c0-35.3-28.7-64-64-64H64zm280 72a24 24 0 1 1 0 48 24 24 0 1 1 0-48zm56 24a24 24 0 1 1 48 0 24 24 0 1 1 -48 0z"/></svg>
                            <h3 class="main-page-part-two-info-card-title">Мощные серверы</h3>
                            <p class="main-page-part-two-info-card-desc">Мы используем только самые лучшие серверы для комфортной и гарантированной работы всего сайта</p>
                        </div>
                        <div class="main-page-part-two-info-card">
                            <svg aria-hidden="true" width="30" height="30" viewBox="0 0 640 512"><path d="M72 88a56 56 0 1 1 112 0A56 56 0 1 1 72 88zM64 245.7C54 256.9 48 271.8 48 288s6 31.1 16 42.3V245.7zm144.4-49.3C178.7 222.7 160 261.2 160 304c0 34.3 12 65.8 32 90.5V416c0 17.7-14.3 32-32 32H96c-17.7 0-32-14.3-32-32V389.2C26.2 371.2 0 332.7 0 288c0-61.9 50.1-112 112-112h32c24 0 46.2 7.5 64.4 20.3zM448 416V394.5c20-24.7 32-56.2 32-90.5c0-42.8-18.7-81.3-48.4-107.7C449.8 183.5 472 176 496 176h32c61.9 0 112 50.1 112 112c0 44.7-26.2 83.2-64 101.2V416c0 17.7-14.3 32-32 32H480c-17.7 0-32-14.3-32-32zm8-328a56 56 0 1 1 112 0A56 56 0 1 1 456 88zM576 245.7v84.7c10-11.3 16-26.1 16-42.3s-6-31.1-16-42.3zM320 32a64 64 0 1 1 0 128 64 64 0 1 1 0-128zM240 304c0 16.2 6 31 16 42.3V261.7c-10 11.3-16 26.1-16 42.3zm144-42.3v84.7c10-11.3 16-26.1 16-42.3s-6-31.1-16-42.3zM448 304c0 44.7-26.2 83.2-64 101.2V448c0 17.7-14.3 32-32 32H288c-17.7 0-32-14.3-32-32V405.2c-37.8-18-64-56.5-64-101.2c0-61.9 50.1-112 112-112h32c61.9 0 112 50.1 112 112z"/></svg>
                            <h3 class="main-page-part-two-info-card-title">Команда</h3>
                            <p class="main-page-part-two-info-card-desc">Лучшая команда специалистов которая поддерживает и развивает сайт для вас и вашего удобства</p>
                        </div>
                        <div class="main-page-part-two-info-card">
                            <svg aria-hidden="true" width="30" height="30" viewBox="0 0 512 512"><path d="M78.6 5C69.1-2.4 55.6-1.5 47 7L7 47c-8.5 8.5-9.4 22-2.1 31.6l80 104c4.5 5.9 11.6 9.4 19 9.4h54.1l109 109c-14.7 29-10 65.4 14.3 89.6l112 112c12.5 12.5 32.8 12.5 45.3 0l64-64c12.5-12.5 12.5-32.8 0-45.3l-112-112c-24.2-24.2-60.6-29-89.6-14.3l-109-109V104c0-7.5-3.5-14.5-9.4-19L78.6 5zM19.9 396.1C7.2 408.8 0 426.1 0 444.1C0 481.6 30.4 512 67.9 512c18 0 35.3-7.2 48-19.9L233.7 374.3c-7.8-20.9-9-43.6-3.6-65.1l-61.7-61.7L19.9 396.1zM512 144c0-10.5-1.1-20.7-3.2-30.5c-2.4-11.2-16.1-14.1-24.2-6l-63.9 63.9c-3 3-7.1 4.7-11.3 4.7H352c-8.8 0-16-7.2-16-16V102.6c0-4.2 1.7-8.3 4.7-11.3l63.9-63.9c8.1-8.1 5.2-21.8-6-24.2C388.7 1.1 378.5 0 368 0C288.5 0 224 64.5 224 144l0 .8 85.3 85.3c36-9.1 75.8 .5 104 28.7L429 274.5c49-23 83-72.8 83-130.5zM56 432a24 24 0 1 1 48 0 24 24 0 1 1 -48 0z"/></svg>
                            <h3 class="main-page-part-two-info-card-title">Инструменты</h3>
                            <p class="main-page-part-two-info-card-desc">Мы используем только самые лучшие передовые технологии и инструменты</p>
                        </div>
                    </div>
                    <h4>Следите за нашим блогом</h4>
                    <div class="main-page-part-two-posts">
                        {% for post in best_posts %}
                        <div class="main-page-part-two-post">
                            <div class="card bg-body-tertiary mt-2 p-2" style="border-radius: 8px; box-shadow: 0 1px 2px 0 rgba(0,0,0,.16); align-items: flex-start;" >
                                <div>
                                    <span style="display: flex;">
                                        <span>
                                            <div class="d-flex">
                                                <div class="main-page-part-two-post-comment-image-link me-1">
                                                    <div style="height: 10px; width: 10px;">
                                                        {% if post.name_user.image %}
                                                        <img src="{{ post.name_user.image.url }}" style="border-radius: 3px; display: block; overflow: hidden; height: 10px; width: 10px;" alt="{{ comment.description }}">
                                                        {% else %}
                                                        <img src="{% static 'images/image_not_found.jpeg' %}" style="border-radius: 3px; display: block; overflow: hidden; height: 10px; width: 10px;" alt="{{ comment.description }}">
                                                        {% endif %}
                                                    </div>   
                                                </div>
                                                <h2 style="white-space: nowrap; font-size: .35rem; font-weight: 700; line-height: 11px;">{{ post.name_user.get_username }}</h2>
                                            </div>
                                            <div style="display: flex;"> 
                                                <a href="{% url 'blog:post' post.slug %}" class="link-underline link-underline-opacity-0 text-black" style="margin-right: 3px">
                                                    <div style="font-size: .3125rem; font-weight: 500; line-height: .0375rem;">
                                                        {% if post.is_edit %}
                                                        {{ post.text_to_edit }} {{ post.time_edit }}
                                                        {% else %}
                                                        {{ post.text_to_post }} {{ post.time_published }}
                                                        {% endif %}
                                                    </div>
                                                </a>
                                                <span style="display: flex; align-items: center;">
                                                    <span style="font-size: .3125rem; font-weight: 700; line-height: 0.3;">Количество просмотров:</span>
                                                    <span style="margin-left: 2px; font-size: .3125rem; font-weight: 700; line-height: 0.3;">{{ post.views }}</span>
                                                </span>
                                            </div>
                                        </span> 
                                    </span>
                                </div>
                                <div style="margin-top: 7px;">
                                    <h6 class="card-title" style="font-size: 7px;">{{ post.title }}</h6>
                                </div>
                                <a href="{% url 'blog:post' post.slug %}" style="max-height: none; padding: 2px 0; position: relative;">
                                    <div style="font-size: 0.5rem; line-height: 0.5px; overflow-wrap: break-word;">
                                        <figure style="margin: 0;">
                                            {% if post.image %}
                                            <img src="{{ post.image.url }}" style="cursor: pointer; max-width: 100%; height: auto; vertical-align: middle; overflow: hidden;" alt="{{ post.title }}">
                                            {% else %}
                                            <img src="{% static 'images/image_not_found.jpeg' %}" style="cursor: pointer; max-width: 100%; height: 214px; vertical-align: middle;" alt="{{ post.title }}">
                                            {% endif %}
                                        </figure>
                                    </div>
                                </a>
                                <p style="margin-top: 4px; font-size: 0.5rem; line-height: 2px;">{{ post.description|truncatechars:70 }}</p>
                                <div style="padding-top: 1px; border-top: 1px solid transparent; display: flex; justify-content: flex-start; width: 100%; font-size:5px">
                                    <div>
                                        <a class="link-underline link-underline-opacity-0 text-black" href="{% url 'blog:post' post.slug %}">Комментарии: {{ post.comment_count }}</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </section>
    </div>
</div>
{% endblock content %}